# Generated by Django 3.1.8 on 2021-05-03 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='fname')),
                ('middle_name', models.CharField(max_length=50, verbose_name='mname')),
                ('last_name', models.CharField(max_length=50, verbose_name='lname')),
                ('birthdate', models.DateField(verbose_name='bday')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Man'), ('F', 'Woman')], max_length=1, null=True, verbose_name='sex')),
                ('profession', models.CharField(max_length=50, verbose_name='profession')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='code')),
                ('quarantine_ends', models.DateField(verbose_name='freedom')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
