# Generated by Django 3.1.8 on 2021-05-03 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attended', models.DateField(auto_now_add=True, verbose_name='date_attend')),
                ('event_type', models.CharField(choices=[('MA', 'Mass'), ('B', 'Baptism'), ('MAR', 'Marriage'), ('F', 'Funeral'), ('O', 'Others')], default='MA', max_length=3, verbose_name='event')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
    ]
