# Generated by Django 3.1.8 on 2021-05-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True, verbose_name='date_record')),
                ('close_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_user_ID', to='user.user')),
                ('covid_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covid_user_ID', to='user.user')),
            ],
        ),
    ]
