# Generated by Django 3.1.8 on 2021-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('close_contact', '0002_closecontact_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closecontact',
            name='date_recorded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
