# Generated by Django 3.1.8 on 2021-05-03 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_swabbed', models.DateField(verbose_name='date_swabbed')),
                ('covid_status', models.TextField(choices=[('P', 'Positive'), ('N', 'Negative')], default='N', verbose_name='covid_status')),
                ('date_recorded', models.DateField(auto_now_add=True, verbose_name='date_record')),
                ('health_status', models.TextField(choices=[('S', 'Symptomatic'), ('A', 'Asymptomatic')], default='A', verbose_name='health_status')),
                ('covid_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
