# Generated by Django 3.1.8 on 2021-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='covid_status',
            field=models.TextField(choices=[('P', 'Positive'), ('N', 'Negative')], default='N'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_recorded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_swabbed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='health_status',
            field=models.TextField(choices=[('S', 'Symptomatic'), ('A', 'Asymptomatic')], default='A'),
        ),
    ]
