# Generated by Django 3.1.8 on 2021-05-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Woman')], max_length=1, null=True, verbose_name='sex'),
        ),
    ]
